### ISSUE TITLE
Bump the MSRV to 1.56?

### ISSUE THREAD

**Issue by woodruffw** [str4d/pinentry-rs#12]
Hey @str4d!

I'm looking at doing some transitive dep updates, and it looks like the current MSRV (1.51) will become a bit of a hurdle: bumping `secrecy` to `0.10` requires a version of `zeroize` that has `edition = 2021`, meaning that the current MSRV can't build it.

TL;DR: in order to keep `zeroize` and `secrecy` up-to-date (making it easier to bump them in downstream crates), `pinentry` would have to move to a MSRV 1.56.

Thoughts? If you don't mind a MSRV bump, I'm happy to include it in a dep bump PR.

**Comment by woodruffw** [comment]
For full tracing:

1. `zeroize 0.10.2` requires `secrecy 1.6`: https://github.com/iqlusioninc/crates/blob/2835a08e8fd085798805c84ee746836eb6154d50/secrecy/Cargo.toml#L21
2. `secrecy 1.6` and newer require Rust 2021: https://github.com/RustCrypto/utils/blob/a650145266d1353e11b1d3dae92c0ceb67254e7d/zeroize/Cargo.toml#L17

**Comment by str4d** [comment]
`secrecy 0.10` actually has an MSRV of 1.60, so that's what we will move to next.

**Comment by str4d** [comment]
Closed by #13.
